In [1]:
import numpy as np
import xarray as xr

In [4]:
ds=xr.open_dataset('https://salishsea.eos.ubc.ca/erddap/griddap/ubcSSnBathymetry2V1')

In [5]:
ds

<xarray.Dataset>
Dimensions:     (gridX: 398, gridY: 898)
Coordinates:
  * gridY       (gridY) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
  * gridX       (gridX) int16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
Data variables:
    longitude   (gridY, gridX) float32 ...
    latitude    (gridY, gridX) float32 ...
    bathymetry  (gridY, gridX) float64 ...
Attributes:
    acknowledgement: MEOPAR, ONC, Compute Canada
    cdm_data_type: Grid
    comment: Bathymetry, Latitudes and Longitudes
    Conventions: CF-1.6, COARDS, ACDD-1.3
    coverage_content_type: modelResult
    creator_email: sallen@eos.ubc.ca
    creator_name: Salish Sea MEOPAR Project Contributors
    creator_url: https://salishsea-meopar-docs.readthedocs.org/
    drawLandMask: over
    history: [2016-02-05 16:35:19] Created dataset.
[2016-03-02 18:08:56] Changed all variables to zlib=True.
[2016-03-02 18:08:56] Added least_significant_digit=1 and fill_value=0 to bathymetry variable.
[2016-03-03 12:28:37

2 dimensions,2 coordinates, 3 variables

In [6]:
ds.longitude

<xarray.DataArray 'longitude' (gridY: 898, gridX: 398)>
[357404 values with dtype=float32]
Coordinates:
  * gridY    (gridY) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
  * gridX    (gridX) int16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
Attributes:
    _ChunkSize: [898 398]
    colorBarMaximum: 180.0
    colorBarMinimum: -180.0
    long_name: Longitude
    standard_name: longitude
    units: degrees_east
    valid_range: [-126.40029144 -121.31835175]

In [7]:
ds.latitude

<xarray.DataArray 'latitude' (gridY: 898, gridX: 398)>
[357404 values with dtype=float32]
Coordinates:
  * gridY    (gridY) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
  * gridX    (gridX) int16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
Attributes:
    _ChunkSize: [898 398]
    colorBarMaximum: 90.0
    colorBarMinimum: -90.0
    long_name: Latitude
    standard_name: latitude
    units: degrees_north
    valid_range: [ 46.85966492  51.10480118]

In [8]:
ds.bathymetry

<xarray.DataArray 'bathymetry' (gridY: 898, gridX: 398)>
[357404 values with dtype=float64]
Coordinates:
  * gridY    (gridY) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
  * gridX    (gridX) int16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 ...
Attributes:
    _ChunkSize: [898 398]
    colorBarMaximum: 450.0
    colorBarMinimum: 0.0
    colorBarPalette: OceanDepth
    grid: Salish Sea 2
    long_name: Depth of Bottom
    standard_name: sea_floor_depth
    units: m
    valid_range: [   0.  428.]

In [9]:
ds.latitude.shape

(898, 398)

In [10]:
ds.longitude.shape

(898, 398)

In [11]:
ds.bathymetry.shape

(898, 398)

In [12]:
ds.latitude.values

array([[ 46.85966492,  46.86154556,  46.86342621, ...,  47.59721375,
         47.59906769,  47.60092163],
       [ 46.86278915,  46.86481476,  46.86677933, ...,  47.60125732,
         47.60311127,  47.60496521],
       [ 46.86606979,  46.86814499,  46.87015915, ...,  47.60529709,
         47.60715485,  47.60900879],
       ..., 
       [ 50.38191605,  50.38397598,  50.38602448, ...,  51.09400177,
         51.09560776,  51.09720612],
       [ 50.38591766,  50.38798523,  50.39004135, ...,  51.09781265,
         51.0994072 ,  51.10100174],
       [ 50.38992691,  50.39200592,  50.39406967, ...,  51.10162354,
         51.10321808,  51.10480118]], dtype=float32)

In [13]:
ds.longitude.values

array([[-123.42943573, -123.42411804, -123.41880035, ..., -121.32898712,
        -121.32366943, -121.31835175],
       [-123.43196869, -123.42677307, -123.42152405, ..., -121.33235931,
        -121.32704163, -121.32172394],
       [-123.43463898, -123.42948151, -123.42427063, ..., -121.33573151,
        -121.33041382, -121.32509613],
       ..., 
       [-126.39330292, -126.38764191, -126.3819809 , ..., -124.34471893,
        -124.340065  , -124.3354187 ],
       [-126.39678955, -126.39109802, -126.38541412, ..., -124.34797668,
        -124.34333801, -124.3387146 ],
       [-126.40029144, -126.39456177, -126.38883209, ..., -124.35121918,
        -124.34658813, -124.34198761]], dtype=float32)

In [15]:
ds.bathymetry.values

array([[ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       ..., 
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]])