In [7]:
import numpy as np
import xarray as xr

#Data downloaded from http://www.unidata.ucar.edu/software/netcdf/examples/wrfout_v2_Lambert.nc #

In [8]:
ds=xr.open_dataset('wrfout_v2_Lambert.nc')

In [9]:
ds

<xarray.Dataset>
Dimensions:           (Time: 13, bottom_top: 27, bottom_top_stag: 28, ext_scalar: 1, soil_layers_stag: 5, south_north: 60, south_north_stag: 61, west_east: 73, west_east_stag: 74)
Coordinates:
  * Time              (Time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
  * bottom_top        (bottom_top) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * bottom_top_stag   (bottom_top_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 ...
  * ext_scalar        (ext_scalar) int64 0
  * soil_layers_stag  (soil_layers_stag) int64 0 1 2 3 4
  * south_north       (south_north) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * south_north_stag  (south_north_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 ...
  * west_east         (west_east) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * west_east_stag    (west_east_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 ...
Data variables:
    Times             (Time) |S19 b'2000-01-24_12:00:00' ...
    LU_INDEX          (Time, south_north, west_east) float32 16.0 16.

In [10]:
ds.dims

Frozen(SortedKeysDict({'bottom_top': 27, 'south_north': 60, 'south_north_stag': 61, 'soil_layers_stag': 5, 'west_east': 73, 'Time': 13, 'ext_scalar': 1, 'bottom_top_stag': 28, 'west_east_stag': 74}))

#This data has nine dimensions#

In [11]:
ds.data_vars

Data variables:
    Times      (Time) |S19 b'2000-01-24_12:00:00' b'2000-01-24_13:00:00' ...
    LU_INDEX   (Time, south_north, west_east) float32 16.0 16.0 16.0 16.0 ...
    U          (Time, bottom_top, south_north, west_east_stag) float32 -1.06967 ...
    V          (Time, bottom_top, south_north_stag, west_east) float32 -13.5656 ...
    W          (Time, bottom_top_stag, south_north, west_east) float32 -0.0 ...
    PH         (Time, bottom_top_stag, south_north, west_east) float32 0.0 ...
    PHB        (Time, bottom_top_stag, south_north, west_east) float32 0.0 ...
    T          (Time, bottom_top, south_north, west_east) float32 -12.4883 ...
    MU         (Time, south_north, west_east) float32 1876.56 1849.13 ...
    MUB        (Time, south_north, west_east) float32 95000.0 95000.0 ...
    P          (Time, bottom_top, south_north, west_east) float32 1969.13 ...
    PB         (Time, bottom_top, south_north, west_east) float32 99525.0 ...
    FNM        (Time, bottom_top) float3

#All the above displayed are the variables for the data set#

In [12]:
ds.coords

Coordinates:
  * Time              (Time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
  * bottom_top        (bottom_top) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * bottom_top_stag   (bottom_top_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 ...
  * ext_scalar        (ext_scalar) int64 0
  * soil_layers_stag  (soil_layers_stag) int64 0 1 2 3 4
  * south_north       (south_north) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * south_north_stag  (south_north_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 ...
  * west_east         (west_east) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * west_east_stag    (west_east_stag) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 ...

#The above are the coordinates of the data#

In [13]:
ds.attrs

OrderedDict([('TITLE', ' OUTPUT FROM WRF V2.0 MODEL'),
             ('START_DATE', '2000-01-24_12:00:00'),
             ('WEST-EAST_GRID_DIMENSION', 74),
             ('SOUTH-NORTH_GRID_DIMENSION', 61),
             ('BOTTOM-TOP_GRID_DIMENSION', 28),
             ('GRIDTYPE', 'C'),
             ('DYN_OPT', 2),
             ('DIFF_OPT', 0),
             ('KM_OPT', 1),
             ('DAMP_OPT', 0),
             ('KHDIF', 0.0),
             ('KVDIF', 0.0),
             ('MP_PHYSICS', 3),
             ('RA_LW_PHYSICS', 1),
             ('RA_SW_PHYSICS', 1),
             ('SF_SFCLAY_PHYSICS', 1),
             ('SF_SURFACE_PHYSICS', 1),
             ('BL_PBL_PHYSICS', 1),
             ('CU_PHYSICS', 1),
             ('WEST-EAST_PATCH_START_UNSTAG', 1),
             ('WEST-EAST_PATCH_END_UNSTAG', 73),
             ('WEST-EAST_PATCH_START_STAG', 1),
             ('WEST-EAST_PATCH_END_STAG', 74),
             ('SOUTH-NORTH_PATCH_START_UNSTAG', 1),
             ('SOUTH-NORTH_PATCH_END_UNSTAG', 6

#Above is the metadata

# ATTRIBUTES OF VARIABLES

In [14]:
ds.Times

<xarray.DataArray 'Times' (Time: 13)>
array([b'2000-01-24_12:00:00', b'2000-01-24_13:00:00',
       b'2000-01-24_14:00:00', b'2000-01-24_15:00:00',
       b'2000-01-24_16:00:00', b'2000-01-24_17:00:00',
       b'2000-01-24_18:00:00', b'2000-01-24_19:00:00',
       b'2000-01-24_20:00:00', b'2000-01-24_21:00:00',
       b'2000-01-24_22:00:00', b'2000-01-24_23:00:00',
       b'2000-01-25_00:00:00'], 
      dtype='|S19')
Coordinates:
  * Time     (Time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12

This data has been captured for 13 time intervals, numbered zero to twelve, from 01/24/2000 12 noon to midnight of 01/25/2000 respectively#

In [15]:
ds.LU_INDEX

<xarray.DataArray 'LU_INDEX' (Time: 13, south_north: 60, west_east: 73)>
array([[[ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        ..., 
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  5.,   5.,   5., ...,  16.,  16.,  16.]],

       [[ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        ..., 
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  5.,   5.,   5., ...,  16.,  16.,  16.]],

       [[ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        [ 16.,  16.,  16., ...,  16.,  16.,  16.],
        ..., 
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  2.,   5.,   5., ...,  16.,  16.,  16.],
        [  5.,

#This "Land Use Category" is a function of three axis : time,south_north,west_east

In [26]:
ds.U

<xarray.DataArray 'U' (Time: 13, bottom_top: 27, south_north: 60, west_east_stag: 74)>
array([[[[ -1.06967402e+00,  -4.10358071e-01,   2.79431820e-01, ...,
           -6.67915010e+00,  -6.85910463e+00,  -7.07047939e+00],
         [ -7.91599751e-01,  -2.26073503e-01,   3.66212606e-01, ...,
           -6.46713161e+00,  -6.63222551e+00,  -6.86797953e+00],
         [ -4.41465139e-01,   3.54691669e-02,   5.09744644e-01, ...,
           -6.25346756e+00,  -6.43438959e+00,  -6.68070793e+00],
         ..., 
         [  4.34557533e+00,   4.70250082e+00,   4.43125439e+00, ...,
            8.57912827e+00,   8.19622040e+00,   7.38154697e+00],
         [  4.36154366e+00,   4.51428413e+00,   4.20090389e+00, ...,
            7.51440668e+00,   7.31502151e+00,   6.67618370e+00],
         [  3.27629757e+00,   2.75278544e+00,   2.31950283e+00, ...,
            6.61795616e+00,   6.46919727e+00,   6.00189114e+00]],

        [[ -1.31678331e+00,  -5.72844207e-01,   2.07816660e-01, ...,
           -6.94556904e

In [18]:
ds.LU_INDEX.values

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ..., 
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True, 

In [17]:
ds.U.values

array([[[[ -1.06967402e+00,  -4.10358071e-01,   2.79431820e-01, ...,
           -6.67915010e+00,  -6.85910463e+00,  -7.07047939e+00],
         [ -7.91599751e-01,  -2.26073503e-01,   3.66212606e-01, ...,
           -6.46713161e+00,  -6.63222551e+00,  -6.86797953e+00],
         [ -4.41465139e-01,   3.54691669e-02,   5.09744644e-01, ...,
           -6.25346756e+00,  -6.43438959e+00,  -6.68070793e+00],
         ..., 
         [  4.34557533e+00,   4.70250082e+00,   4.43125439e+00, ...,
            8.57912827e+00,   8.19622040e+00,   7.38154697e+00],
         [  4.36154366e+00,   4.51428413e+00,   4.20090389e+00, ...,
            7.51440668e+00,   7.31502151e+00,   6.67618370e+00],
         [  3.27629757e+00,   2.75278544e+00,   2.31950283e+00, ...,
            6.61795616e+00,   6.46919727e+00,   6.00189114e+00]],

        [[ -1.31678331e+00,  -5.72844207e-01,   2.07816660e-01, ...,
           -6.94556904e+00,  -7.17459583e+00,  -7.48022175e+00],
         [ -9.60450649e-01,  -3.13160598e-01,

In [25]:
ds.QVAPOR.values

array([[[[  8.18111189e-03,   8.27421620e-03,   8.34916998e-03, ...,
            1.52326059e-02,   1.53132062e-02,   1.53556382e-02],
         [  7.80048734e-03,   7.84683973e-03,   7.92800449e-03, ...,
            1.52496994e-02,   1.53513756e-02,   1.54279200e-02],
         [  7.44797429e-03,   7.45457271e-03,   7.50619732e-03, ...,
            1.53345931e-02,   1.54509852e-02,   1.55490711e-02],
         ..., 
         [  7.65469740e-04,   7.31259177e-04,   7.79131136e-04, ...,
            8.56955908e-03,   9.08009056e-03,   9.72260442e-03],
         [  8.01036018e-04,   8.06693046e-04,   7.78907561e-04, ...,
            8.51848628e-03,   9.00840759e-03,   9.67216212e-03],
         [  8.04155541e-04,   8.01664894e-04,   7.27793085e-04, ...,
            8.46679695e-03,   8.91081244e-03,   9.52454098e-03]],

        [[  6.76379632e-03,   6.77180896e-03,   6.76226150e-03, ...,
            1.39424177e-02,   1.39778014e-02,   1.39935743e-02],
         [  6.39739772e-03,   6.37436984e-03,

In [34]:
ds.U.shape

(13, 27, 60, 74)

#The shape of U ndarray is as above

In [46]:
print(ds.U[3][26][59][70])

<xarray.DataArray 'U' ()>
array(17.00162696838379, dtype=float32)
Coordinates:
    Time            int64 3
    bottom_top      int64 26
    south_north     int64 59
    west_east_stag  int64 70
Attributes:
    FieldType: 104
    MemoryOrder: XYZ
    description: x-wind component
    units: m s-1
    stagger: X


#Accessing a particular element value from the 4d array of variable "U". "3" corresponds to Times,"26" corresponds to bottom_top etc... 

In [48]:
ds.U>=17

<xarray.DataArray 'U' (Time: 13, bottom_top: 27, south_north: 60, west_east_stag: 74)>
array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ..., 
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ..., 
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         